site_name: vodscrepe
nav:
  - Overview: README.md
  - Documentation: documentation.md
repo_url: https://github.com/dawsonbooth/vodscrepe/
site_url: https://dawsonbooth.github.io/vodscrepe/

markdown_extensions:
  - toc:
      permalink: 🔗

theme:
  name: readthedocs